image: cypress/base:10

# Shared steps.
stepBuild: &stepBuild
  step:
    name: Build and Validate
    caches:
      - node
      - npm
      - cypress
    script:
      - npm --version
      - npm ci
      - npx gulp validate
      - npx gulp compile
    artifacts:
      - public/**

stepTests: &stepTests
  step:
    name: E2E Tests with Cypress
    caches:
      - node
      - npm
      - cypress
    script:
      - npm run e2e:ci -- --config video=false # Disable video recording


pipelines:
  default:
    - <<: *stepBuild
    - <<: *stepTests
  branches:
    master:
      - <<: *stepBuild
      - <<: *stepTests
      - step:
          name: Deploy to AWS
          image: mesosphere/aws-cli
          deployment: production
          script:
            - cd public
            # Be sure to add environment variables for AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION, S3_BUCKET
            - aws s3 sync . s3://$S3_BUCKET --delete --exclude '*.svg'
            - aws s3 sync . s3://$S3_BUCKET --delete --exclude '*' --include '*.svg' --content-type 'image/svg+xml'

definitions:
  caches:
    npm: ~/.npm
    cypress: ~/.cache
