# Config options can be found at https://github.com/ucdavis/ucd-theme-tasks/blob/master/docs/config.md
# This config may be overridden by creating a gulp-config.local.yml file
css:
  enabled: true
  src:
    - source/sass/**/*.scss
  vendor:
    - source/css/vendor/**/*.css
    - '!node_modules/slick-carousel/slick/slick-theme.css'
  dest: public/css/
  lint:
    extraSrc:
      - '!source/sass/0_utility/utility_helpers/_u-space.scss'
  outputStyle: compressed

js:
  enabled: true
  src:
    - source/js/**/*.js
    - source/js/vendor/**/*.js
  externals: false
  dest: public/js/
  eslint:
    enabled: false
    extraSrc:
      - '!source/js/vendor/**/*.js'

nodeFiles:
  enabled: true

browserSync:
  enabled: true
  startPath: 'public'
#  browser: ['chrome'] # Use this instead of 'Chrome Browser' if on Windows.

themeSync:
  enabled: false
  newsite: false
  # dest: '../theme/' # This is the destination of the CMS theme these source files will be ported to

patternLab:
  enabled: true
